language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    - PYTHONPATH="/home/travis/build/json-transformations/jsonflatten"
install: "pip install jsoncut pytest-cov pytest-pep8 coveralls"
script: py.test --cov=jsonflatten --pep8
after_success:
- coveralls
